import "./globals.css";
import {
  ethnocentric,
  ibmPlexMono,
  loraSerif,
  outfitSans,
} from "@/assets/fonts/index.config";
import { Toaster } from "@/components/ui/toaster";
import SessionProvider from "@/providers/session-provider";
import { SolanaWalletProvider } from "@/providers/solana-wallet-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "PlutonAI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // suppressHydrationWarning
    >
      <body
        className={`${outfitSans.variable} ${loraSerif.variable} ${ethnocentric.variable} ${ibmPlexMono.variable} font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          {/* <SessionProvider> */}
          <SolanaWalletProvider>{children}</SolanaWalletProvider>
          {/* </SessionProvider> */}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
